# Generated by Django 4.2.3 on 2023-07-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityuser',
            name='user_type',
            field=models.CharField(choices=[('U', 'User'), ('O', 'Organization')], default='User', max_length=1),
        ),
    ]
