# Generated by Django 4.2.3 on 2023-07-26 09:02

import charity_app.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_charityuserprofile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(8), charity_app.accounts.validators.name_validator])),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10), charity_app.accounts.validators.phone_number_validator])),
                ('information', models.TextField(max_length=300)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='organization-photo/')),
            ],
        ),
    ]
