# Generated by Django 4.2.3 on 2023-07-26 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organizationuserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationuserprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='organizationuserprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
