# Generated by Django 4.2.3 on 2023-08-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_organizationuserprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityuserprofile',
            name='information',
            field=models.TextField(default=50, max_length=300),
            preserve_default=False,
        ),
    ]
