# Generated by Django 4.2.3 on 2023-08-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_charityuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityuser',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
