# Generated by Django 4.2.3 on 2023-08-07 20:36

import charity_app.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_charityuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuserprofile',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(8), charity_app.accounts.validators.organization_name_validator]),
        ),
    ]
