# Generated by Django 4.2.4 on 2023-08-14 15:38

import charity_app.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_charityuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityuser',
            name='user_type',
            field=models.CharField(choices=[('U', 'User'), ('O', 'Organization')], default=charity_app.accounts.models.UserType['User'], max_length=1),
        ),
    ]
