# Generated by Django 4.2.4 on 2023-08-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_charityuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityuser',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
