# Generated by Django 4.2.3 on 2023-08-06 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogs'),
        ),
    ]
