# Generated by Django 4.2.4 on 2023-08-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('LFV', 'Looking_For_Volunteers'), ('SFA', 'Seeking_Financial_Aid'), ('SMA', 'Seeking_Material_Aid')], max_length=22),
        ),
    ]
